version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
permissions:
   - object: *.sh
     mode: 770
hooks:
  AfterInstall:
    - location: after-install.sh
      timeout: 60
  ValidateService:
    - location: validate.sh
      timeout: 60
